# Generated by Django 3.2.4 on 2021-09-01 01:42

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='images/'),
        ),
    ]
