# Generated by Django 3.2.4 on 2021-09-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
