# Generated by Django 3.2.4 on 2021-09-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210903_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
