# Generated by Django 3.2.4 on 2021-09-08 22:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210908_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
